CREATE TABLE additional_passenger (
  idpassenger int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  firstname varchar(45) NOT NULL,
  lastname varchar(45) NOT NULL,
  birthdate date NOT NULL,
  pass_ser varchar(45) NOT NULL,
  pass_num varchar(45) NOT NULL,
  expirydate date NOT NULL,
  email varchar(45) UNIQUE DEFAULT NULL,
  PRIMARY KEY (idpassenger)
);

CREATE TABLE person (
  idperson int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  email varchar(255) NOT NULL UNIQUE ,
  password varchar(32) NOT NULL,
  creation_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  mgr boolean NOT NULL DEFAULT '0',
  firstname varchar(45) NOT NULL,
  lastname varchar(45) NOT NULL,
  birthdate date NOT NULL,
  pass_ser varchar(45) NOT NULL,
  pass_num varchar(45) NOT NULL,
  expirydate date NOT NULL,
  PRIMARY KEY (idperson)
);



CREATE TABLE booking (
  idbooking int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  total_price float NOT NULL,
  personid int NOT NULL,
  PRIMARY KEY (idbooking),
  FOREIGN KEY (personid) REFERENCES person (idperson)
);

CREATE TABLE flight (
  idflight int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  city_from varchar(45) NOT NULL,
  city_to varchar(45) NOT NULL,
  airport_from varchar(45) NOT NULL,
  airport_to varchar(45) NOT NULL,
  max_sits int NOT NULL,
  flight_date date NOT NULL,
  PRIMARY KEY (idflight)
);

CREATE TABLE seat (
  idseat int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  seatnumber int NOT NULL,
  available boolean NOT NULL,
  price float NOT NULL,
  flightid int NOT NULL,
  PRIMARY KEY (idseat),
  FOREIGN KEY (flightid) REFERENCES flight (idflight)
);

CREATE TABLE ticket (
  idticket int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  extra_lug int DEFAULT NULL,
  creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  seatid int NOT NULL,
  bookingid int NOT NULL,
  passengerid int DEFAULT NULL,
  PRIMARY KEY (idticket),
  FOREIGN KEY (bookingid) REFERENCES booking (idbooking),
  FOREIGN KEY (passengerid) REFERENCES additional_passenger (idpassenger),
  FOREIGN KEY (seatid) REFERENCES seat (idseat)
);


